- .github/CODEOWNERS
- Dockerfile
Previously, when a branch already existed the was being pushed,
the import.py script used the Gitea API to enable pushes to the
repository after branches had been protected from a previous import.
When the branch does not change, ie a new version of CSM, but not a
new version of csm-import, a force push happens, but branch protections
that allow pushing on a protected branch do not allow force pushes.
To remedy this, instead of just enabling push, remove the branch
protections altogether, force push the branch, and then re-enable
branch protections if requested.
This is a backwards compatible change. We need to force this repo to rebuild to pick up the changes, so an update to the CODEOWNERS file (a non-deliverable fix) has been added to force the rebuild.
* Resolves …
> CASMINST-3525: rebuild for new version of cf-gitea-import

- Dockerfile
Recently the RPM repo layout on algol60 was changed. Previously all stable hpe RPMs were put into a single repo. The problem there was that this lumped together our RPMs build for different SLES versions. As a result, the repos were split out so that RPMs were published to a repo specific to their target OS. However, the previous repo was not removed. Therefore all builds pointing to it still worked...until one of them wanted to install a recent version of an RPM, one which was built and published using this new system, and therefore did not exist in the old repo.
That was the case for two of our repos -- ansible-execution-environment and csm-config. This PR just updates the repo URL in the Dockerfile to point to the updated repo location. This will fix the build breaks we are already …
> CASMCMS-7711: Update RPM repo URL to new location

- ansible/vars/csm_packages.yml
This change removes the old HMS CT test RPM called **hms-ct-test-crayctldeploy** that has been replaced in csm-1.2 (and beyond) and adds the new HMS CT test RPMs to the list of Ansible CSM packages.
* Resolves CASMTRIAGE-2815 in master.
Not sure how to test this, trying to fix "No provider of hms-ct-test-crayctldeploy" errors reported in CASMTRIAGE-2815 by the ansible-0 log as part of the CFS session.
Was a fresh Install tested? N
Was an Upgrade tested? N
Was a Downgrade tested? N
Low risk, attempts to fix something that is currently broken.
> CASMTRIAGE-2815 Update list of CSM packages with new HMS test RPMs master

- ansible/vars/csm_packages.yml
This change removes the old HMS CT test RPM called **hms-ct-test-crayctldeploy** that has been replaced in csm-1.2 (and beyond) and adds the new HMS CT test RPMs to the list of Ansible CSM packages.
* Resolves CASMTRIAGE-2815 in csm-1.2.
Not sure how to test this, trying to fix "No provider of hms-ct-test-crayctldeploy" errors reported in CASMTRIAGE-2815 by the ansible-0 log as part of the CFS session.
Was a fresh Install tested? N
Was an Upgrade tested? N
Was a Downgrade tested? N
Low risk, attempts to fix something that is currently broken.
> CASMTRIAGE-2815 Update list of CSM packages with new HMS test RPMs csm-1.2

- ansible/roles/csm.ncn.move_first_master/tasks/main.yml
* Resolves [CASMINST-3792](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3792)
Minimal testing of the ansible (craystack).
* `craystack`
Ran the ansible in isolation to make sure i've used cron and copy modules correctly.
Low
C02YT3JRLVCJ:node-image-build bklein$ vim /tmp/foo
C02YT3JRLVCJ:node-image-build bklein$ cat /tmp/foo
(1.2): https://github.com/Cray-HPE/csm-config/pull/38
(master):
When promoting a new first master, we also need to enable the cronjob kicker script in cron.
* Resolves [CASMINST-3792](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3792)
Minimal testing of the ansible (craystack).
* `craystack`
Ran the ansible in isolation to make sure i've used cron and copy modules correctly.
Low
> Enable the cronjob kicker on new master node

- Dockerfile
- Makefile
- README.md
- ansible/ncn-master_nodes.yml
- ansible/ncn-storage_nodes.yml
- ansible/ncn-worker_nodes.yml
- ansible/packages.yml
- ansible/roles/csm.gpg_keys/README.md
- ansible/roles/csm.gpg_keys/defaults/main.yml
- ansible/roles/csm.gpg_keys/files/csm_read_secrets_backport.py
- ansible/roles/csm.gpg_keys/meta/main.yml
- ansible/roles/csm.gpg_keys/tasks/main.yml
- ansible/roles/csm.packages/README.md
- ansible/roles/csm.packages/defaults/main.yml
- ansible/roles/csm.packages/meta/main.yml
- ansible/roles/csm.packages/tasks/main.yml
- ansible/vars/csm_packages.yml
- ansible/vars/csm_repos.yml
- kubernetes/csm-config/Chart.yaml
- kubernetes/csm-config/values.yaml
- runLint.sh
- update_versions.conf
This is a backwards-compatible backport to bring in the `csm.packages` functionality that was introduced in CSM 1.2.
Note that we have not formally backported the `csm_read_secrets` module from the csm-ssh-keys repository as this will require rebuilds and manifest updates for AEE, CFS Operator, and this repository and building a new RPM in that repo could affect other product teams which have not pinned their version of the csm-ssh-keys RPM. Instead, we have included the `files/csm_read_secrets_backport.py` script to mimic the functionality of the CSM 1.2 version of the module. This change is encapsulated in 64a0cdb304260b388edc22a4e043274c9ba09f29.
* Resolves [CASMINST-3664](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3664)
* Change will also be needed in the CSM manifest
* …
> Backport csm.packages to install loftsman in CSM 1.0.10

- ansible/vars/csm_packages.yml
Add loftsman to the list of packages to install/upgrade during
Management node configuration/NCN personalization. Loftsman
needed to be upgraded in the CSM 1.0.10 release, and in order to
ensure that the latest version gets upgraded on future releases
and patches, add loftsman to future proof it.
Backwards compatible change.
* Resolves CASMINST-3811
This was tested in CASMINST-3664 (version 1.6.28 of csm-config).
Low, typically loftsman will be installed in the NCN image as the latest version.
> CASMINST-3811: Add loftsman to csm_packages

- update_external_versions.conf
We needed to update the version of alpine that cf-gitea-import was using to resolve CVE vulnerabilities.  This rebuild pulls in the new base image.
* Resolves [CASMINST-4145](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4145)
* `Drax`
After the new image was built, I used snyk to insure the updated image was free of vulnerabilities.  We installed the new image on Drax and insured that the gitea import worked correctly.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? N
- Was upgrade tested? If not, why? Y
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this change? N
This is a low risk change as it just …
> CASMINST-4145 - Include updated version of cf-gitea-import to resolve CVEs.

- README.md
- kubernetes/csm-config/Chart.yaml
- update_external_versions.conf
Bring in the new cf-gitea-import v1.6.0 and cray-import-config v3.0.3 base chart to fix CASMCMS-7890. The csm-config chart will now retain the same commit id when a chart is re-run with the same product version. This will remove the need for users to update their CSM configuration layer commit id in CFS despite having the same content.
* Resolves CASMCMS-7890
* `mug`
Ran csm-config chart with loftsman changing the chart version and leaving the product version the same. Verified in the product catalog that the commit was unchanged by default, and changed when `CF_IMPORT_FORCE_EXISTING_BRANCH` was specified.
No
> CASMCMS-7890

- ansible/roles/csm.ssh_keys/tasks/main.yml
We have seen at least a couple of installs where SSH was broken between NCNs after NCN personalization was run. The cause was that no newline was present at the end of the SSH key files, which causes SSH to view the files as being in an invalid format. The lack of a trailing newline was because the key values were stored in vault with no ending newline. This was done due to user error (or user unawareness that it mattered).
I have discovered that having extra newlines at the end of the file is not a problem, however. So I propose to modify the Ansible play so that it adds a newline at the end of the files. Worst case it is superfluous, but in the case that the user omitted it, this would correct the problem. I can see no reason why a user would deliberately want their SSH key files to be …
> CASMCMS-7990: Append newline to SSH key files

- ansible/enable_chn.yml
- ansible/roles/csm.ncn.enable_chn/README.md
- ansible/roles/csm.ncn.enable_chn/defaults/main.yml
- ansible/roles/csm.ncn.enable_chn/tasks/main.yml
Ansible role to determine whether the bifurcated CAN is configured to use CAN or CHN by reading the systemDefaultRoute property from the BICAN SLS network. In the case that CHN is defined configure the CHN IP addresses on the worker HSN interfaces.
HSN interface configuration on the NCNs now requires SHS *and* COS to be installed and configured correctly therefore this role should be configured as a standalone layer to be run after the SHS and COS layers have run.
The reason for this is due to the following actions taken by the SHS and COS layers.
* SHS layer restarts openibd which deletes the existing HSN interface configuration
* COS second layer (ncn-final.yml) restarts the `cray-ifscan` service then waits up to 5 minutes for the HSN interfaces to be configured before installing and …
> CASMNET-1528 - BI-CAN: Create CFS play that will setup CHN IP on NCNs after HSN install

- ansible/compute_nodes.yml
- ansible/ncn-master_nodes.yml
- ansible/ncn-storage_nodes.yml
- ansible/ncn-worker_nodes.yml
- ansible/packages.yml
- ansible/roles/csm.packages/tasks/main.yml
This adds a new playbook that can be run in order to add the cfs-state-reporter and bos-reporter packages so that they can be removed the image recipe.  There will be a corresponding change in the docs to add this layer in image customization.
The new playbook will not work completely until the bos-v2 branch is merged and deployments include the bos-reporter in nexus.
* Resolves CASMCMS-6989
* Hela
Tested image creation with the new layer.  The test did fail on bos-reporter because it is not yet available.
None
> CASMCMS-6989: Adds playbook for adding cfs and bos packages to compute

- CHANGELOG.md
- update_external_versions.conf
I realized that csm-config was still using the old versions of cf-gitea-import and csm-ssh-keys, even though there have been changes made to those both relatively recently. This PR updates it to using the newer versions.
Just build testing so far.
Probably riskier to not use the new versions, since we're making changes to them for a reason.
> CASMCMS-8104: Use updated versions of cf-gitea-import and csm-ssh-keys

- CHANGELOG.md
- ansible/vars/csm_packages.yml
The HMS CT test RPMs are no longer used in CSM 1.3. This PR stops them from trying to be installed during NCN personalization. Without this change, NCN personalization fails, since the RPMs are not there.
This problem was reported on tyr. I hot patched this change into the csm config repo on tyr and verified that it fixed the problem.
Low risk -- just removing RPMs from the list. Nothing new is added.
> CASMINST-5090: Remove HSM CT test RPMs from CSM packages list

- CHANGELOG.md
- ansible/roles/csm.ncn.ca_cert/tasks/main.yml
added conditional to csm.ncn.ca_cert to check for the existence of **certificate_authority.crt** before proceeding.
ncn-personalization halted because the cert didn't exist on disk. Fixes ncn-personalization.
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5187
* surtur
ncn-personalization executed successfully on surtur with this change
Not aware of any risks.
> CASMINST-5187

- CHANGELOG.md
- Dockerfile
The base image for the final layer may or may not have security patches applied, so each time this is built, apply any security patches directly to it here.  This does not rely on the base image being updated to get all patches at the time of the build.
* Resolves [CASMCMS-8099](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8099)
* Build system
The image built with the Jenkins pipeline failed the CVE scan before the changes, and passes after the changes.  There are no code changes, just a base image update so no need to test on-system.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? N
- Was upgrade tested? If not, why? N
- Was downgrade tested? If not, why? N
- Were new tests …
> CASMCMS-8099 - apply security patches to base image.

- CHANGELOG.md
- ansible/ncn-initrd.yml
- ansible/roles/csm.ncn-initrd/README.md
- ansible/roles/csm.ncn-initrd/tasks/main.yml
Provide a role and playbook for creating an NCN initrd.  This is
a helper role for pre-boot NCN image modification.
* Resolves [MTL-1921](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1921)
* `surtur`
See PR comments.
No risks.
> MTL-1921: add csm.ncn-initrd role

- CHANGELOG.md
- ansible/vars/csm_repos.yml
[CASMTRIAGE-4094](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4094) was opened because no source for the cfs-state-reporter RPM was found on a system. It turns out that the SLES SP4 RPMs in the tarball were not getting loaded into Nexus. [CASMINST-5314](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5314) made the changes to get them loaded into Nexus. This PR is modifying csm-config so that it will configure the new repository during NCN personalization.
- Resolves [CASMCMS-8209](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8209).
- Combined with [CASMINST-5314](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5314), resolves [CASMTRIAGE-4094](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4094).
I have not been able to test the actual updated …
> CASMCMS-8209: Add csm-sle15sp4 repo

- CHANGELOG.md
- ansible/vars/csm_packages.yml
Adds the cfs-debugger to the ncn package list
* Resolves CASMCMS-5516
> CASMCMS-5516: Add cfs-debugger to ncn packages

- CHANGELOG.md
- ansible/vars/csm_packages.yml
Install `craycli` and `cray-uai-util` through CSM CFS. Previously this was still being done in the COS kiwi recipe. All other packages from CSM had been migrated to CSM CFS (BOS, CFS, etc).
(cherry picked from commit dcd446cf0d20d110606520e4f6a22d34f11b5f7f)
* Resolves [CASMUSER-3131]
* `baldar`
Upgraded cos-config and created a COS kiwi recipe that did not install `cray-uai-util` or `craycli`. Updated `cos-config` included the change to add these two packages during CFS.
Here are results showing the packages in a running compute (without this change), and the packages installed in the modified image
```
ncn-m001:~ # ssh x8000c0s1b0n1 rpm -qa | egrep "craycli|uai"
cray-uai-util-2.1.0-1.x86_64
craycli-0.66.0-1.x86_64
ncn-m001:~ #
ncn-m001:~ # chroot …
```
> CASMUSER-3131: Install craycli and cray-uai-util with CFS

- CHANGELOG.md
- ansible/csm_packages.yml
Updates Compute and Application node playbooks so that package install will only run during image customization and not at boot time.
This uses different syntax from https://github.com/Cray-HPE/csm-config/pull/93 because older releases of CFS did not support the "cfs_image" host group.
* Resolves CASMTRIAGE-5003
* Surtur
Ran the update against a node to confirm the role did not run
None
> CASMTRIAGE-5003: Only install Compute packages during image customization (csm-1.3)

- CHANGELOG.md
- ansible/csm_packages.yml
Updates Compute and Application node playbooks so that package install will only run during image customization and not at boot time.
* Resolves CASMTRIAGE-5003
* Surtur
Ran the update against a node to confirm the role did not run
None
> CASMTRIAGE-5003: Only install Compute packages during image customization

- CHANGELOG.md
- ansible/ncn-initrd.yml
IUF/sat now modifies storage and master images in addition to worker images. This commit adds the storage and master image classes to the 'hosts' in ncn-initrd.yml to allow an initrd to be created for those image types.
* Resolves [CASMINST-6041](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6041)
* not yet tested
N/A
> CASMINST-6041: allow ncn-initrd.yml to be used with all image types

- CHANGELOG.md
- Dockerfile
This change corrects build failures being seen due to [CASMINST-4829](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4829).
No functional changes -- just changes to where the build looks for a couple of respositories.
- Resolves: [CASMCMS-8441](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8441)
- Caused by: [CASMINST-4829](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4829)
- Blocking being able to build the fix for: [CASMINST-6051](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6051)
No testing beyond making sure the builds now work.
Low risk -- without this change, building doesn't happen.
> CASMCMS-8441: Build Docker image using mirrors of csm-rpms and csm-docker repositories

- CHANGELOG.md
- ansible/csm_packages.yml
[CASMTRIAGE-5050](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5050) was opened because the csm_packages play was failing. The resulting investigation revealed that the play needed the `ansible_distribution` variable to be set, but the play had `gather_facts` set to `no`.
This PR enables fact gathering for that play, but enables the minimum necessary in order to get that variable set (since gathering facts is a performance hit).
- Resolves [CASMTRIAGE-5050](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5050)
- Injected by [CASMCMS-8240](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8240) (c03295cca5823269973e78f1b1c20c4065fdbc32)
I tested on baldar and verified that the play works with these changes made (but does not work with fact-gathering disabled).
Low …
> CASMTRIAGE-5050: Enable targeted fact-gathering in csm_packages.yml

- CHANGELOG.md
- Dockerfile
- ct.yaml
- zypper-docker-build.sh
@dlaine-hpe informed me that as a team, we're trying to avoid using the HPE internal unauthenticated mirrors in our builds, and instead access the original repositories using authentication.
Last week I modified the csm-config repository to use the internal mirrors to avoid a Docker image build failure. Yesterday, with some help from David, I figured out how to modify this repository to do the builds using artifactory authentication. This PR implements that.
Note:
The reason that a new Shell script is introduced is for a few reasons. For one, the necessary credentials are stored in files that are mounted as part of the Dockerfile RUN directive. So their values have to be read from inside of a RUN command. But also, I based my solution partly on what I saw Mikhail did for [a UAI team …
> CASMCMS-8470: Use artifactory authentication instead of unauthenticated mirrors

- CHANGELOG.md
- ansible/enable_chn.yml
To facilitate adding `enable-chn.yml` into default bootprep automation files for NCNs, allow `enable-chn.yml` to be a no-op during CFS Image Customization
* Resolves [CASMNET-2085](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-2085)
* `lemondrop`
Tested an image build using `sat bootprep`. The additional CFS layer shows up in the image build, but it is skipped. Checked all three NCN image builds (kubernetes-worker, kubernetes-master, storage):
```
Running enable_chn.yml from repo https://api-gw-service-nmn.local/vcs/cray/csm-config-management.git
PLAY [Management_Worker:!cfs_image] ********************************************
skipping: no hosts matched
...
Running enable_chn.yml from repo https://api-gw-service-nmn.local/vcs/cray/csm-config-management.git
PLAY …
```
> Allow enable-chn.yml to be a no-op during Image Customization

- CHANGELOG.md
- ansible/vars/csm_packages.yml
- ansible/vars/csm_repos.yml
Adds the `noos` repo (CASMINST-3421) which provides our new `csm-auth-utils` package from MTL-2016.
Requires these to merge _first_, so the package is available. This could have merged at the same time, but I got this PR up late and can't complete the csm-config merge process right now.
> MTL-2016 Add `csm-auth-utils` and `noos` repo

- CHANGELOG.md
- ansible/ncn-sysctl.yml
- ansible/ncn_nodes.yml
- ansible/roles/csm.ncn.sysctl/README.md
- ansible/roles/csm.ncn.sysctl/defaults/main.yml
- ansible/roles/csm.ncn.sysctl/tasks/main.yml
- ansible/roles/csm.ncn.sysctl/vars/main.yml
This PR bring a way to set kernel parameters with sysctl. The role works with both editing images, and running systems.
* Resolves [CASM-4085](https://jira-pro.it.hpe.com:8443/browse/CASM-4085)
* `Mug`
Tested by building images with CFS
> CASM-4085: Add csm.ncn.sysctl role

- .gitignore
- CHANGELOG.md
- ansible/roles/csm.ims-passthrough/README.md
- ansible/roles/csm.ims-passthrough/tasks/main.yml
Included is documentation and a sample role demonstrating proper lookup of environment variables populated by IMS Chroot Jails.
IMS exposes 3 additional environment variables when standing up a chroot environment for an image. Downstream product setup environments should dynamically change as a function of how these environment variables are set up, for both DKMS and ansible architecture support.
The included new role primarily serves as documentation for best case use and lookup of this exposed information.
* Resolves [CASMCMS-8537](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8537)
* Change will also be needed in a newly cut release.
* `mug` and `tyr`
A new test top level playbook was created and run against various host environments; both including …
> CASMCMS-8537: Documentation for using IMS Passthrough variables

- CHANGELOG.md
- ansible/roles/csm.packages/README.md
- ansible/roles/csm.packages/defaults/main.yml
- ansible/vars/csm_packages.yml
The CSM 1.4.1 patch included a new version of the Cray CLI RPM, but it did not get updated on the NCNs even though it was in Nexus and CFS was re-run on the NCNs. It turns out that this RPM is updated on compute nodes by CFS but not NCNs.
This PR adds the Cray CLI RPM to the list of packages that are installed/updated on NCNs. It also includes a few other RPMs that should be updated from Nexus on NCNs, if there are updates available -- the Goss test RPMs, `cfs-state-reporter`, `cfs-trust`, and a few others. I verified that all of these RPMs are listed in the CSM manifests both for Nexus and for the node images.
This also fixes the `csm.packages` role to use the correct default value for the repository list. Previously it defaulted to an empty dictionary, but it is expected to be a list, …
> CASMINST-6532: Add RPMs to list that are installed/updated on nodes; fix default variable value in csm.packages

- CHANGELOG.md
- ansible/csm_packages.yml
- ansible/ncn-master_nodes.yml
- ansible/ncn-storage_nodes.yml
- ansible/ncn-worker_nodes.yml
- ansible/ncn_nodes.yml
- ansible/packages.yml
- ansible/roles/csm.packages/README.md
- ansible/roles/csm.packages/defaults/main.yml
- ansible/vars/csm_packages.yml
This is essentially a backport of https://github.com/Cray-HPE/csm-config/pull/142, with:
* some minor RPM content differences because this is CSM 1.5. 
* splitting up the RPM list into multiple lists to more easily see what is being installed where, and to allow more control when adding new RPMs to the lists (I think some of the missing RPMs on NCNs were caused by confusion about where the package lists would be applied)
> CASMINST-6532: Add RPMs to lists that are installed/updated on nodes; fix default variable value in csm.packages

- CHANGELOG.md
- ansible/ncn-storage_nodes.yml
- ansible/ncn_nodes.yml
- ansible/roles/csm.storage.smartmon/README.md
- ansible/roles/csm.storage.smartmon/tasks/main.yml
- ansible/vars/csm_packages.yml
* Resolves - 
https://jira-pro.it.hpe.com:8443/browse/CASMMON-333
Mug
ncn-m001:~/shreni # kubectl logs -n services jobs/cfs-2f6c447c-dc65-47db-8909-07a136422913 ansible
Inventory generation completed
SSH keys migrated to /root/.ssh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 …
> CASMMON-333: Ansible playbook changes for getting SMART data for upgrade to csm-1.5

- CHANGELOG.md
- ansible/roles/csm.storage.smartmon/tasks/main.yml
Fix filename extension for node-exporter yaml.
* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5793
Fanta re-running play with file renamed:
```
root@ncn-m001 2023-08-01 14:47:05 ~ # /usr/share/doc/csm/scripts/operations/configuration/apply_csm_configuration.sh --config-name "management-csm-${CSM_RELEASE}" --clear-state --xnames x3000c0s15b0n0,x3000c0s13b0n0,x3000c0s17b0n0
Using latest release 1.5.0-beta.29
Using CSM configuration version 1.16.10
Found git commit eb2eb80f88b3e70c9b5636af2a5b3ee4b119b3d3
Creating the configuration file /root/apply_csm_configuration.20230801_145050.Us9FhC/csm-config-1.16.10-F4XQ7H.json
Creating new NCN configuration file /root/apply_csm_configuration.20230801_145050.Us9FhC/new-management-csm-1.5.0-44uWfp.json
Disabling configuration for all listed …
```
> Fix node-exporter filename extension (CASMTRIAGE-5793)

- CHANGELOG.md
- ansible/roles/csm.ncn.sysctl/vars/main.yml
Use `sysctl` settings that were removed in MTL-1974, which were employed for all of CSM's lifetime.
> CASMTRIAGE-5788 Use Pre CSM 1.4 Defaults for ARP sysctl

- CHANGELOG.md
- ansible/csm_packages.yml
- ansible/ncn-master_nodes.yml
- ansible/ncn-storage_nodes.yml
- ansible/ncn-worker_nodes.yml
- ansible/ncn_nodes.yml
- ansible/ncn_sysctl.yml
- ansible/packages.yml
- ansible/roles/csm.ncn.ca_cert/tasks/main.yml
- ansible/roles/csm.ncn.sysctl/README.md
- ansible/roles/csm.ncn.sysctl/defaults/main.yml
- ansible/roles/csm.ncn.sysctl/tasks/main.yml
- ansible/roles/csm.ncn.sysctl/vars/main.yml
- Backport the `csm.ncn.sysctl` role from 1.5 with CASMTRIAGE-5788's fixes
- Invoke the `csm.ncn.sysctl` role in the `ncn_nodes.yml` book as well as all three playbooks invoked by `site.yml`
Extra:
- Replace all `ansible_os_family` and `ansible_distribution` conditionals for `SLE_HPC` with `ansible_distribution_file_variety == "SUSE"`
> CASMTRIAGE-5788 Sysctl role

- CHANGELOG.md
- ansible/vars/csm_packages.yml
CFS is failing in some cases, trying to update the `csm-node-identity` RPM from version 1.0.18 to 1.0.20. Prior to a recent change, CFS was not attempting to update this RPM. The root cause of the failure is not related to CFS, but for this support branch, the simplest fix is to just move CFS back to behaving the way it did before (that is, not upgrading that RPM).
This change isn't needed for the develop branch, because current CSM versions will be starting with a version of that RPM that is not susceptible to that problem.
* Resolves [CASMTRIAGE-5817](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5817)
None yet (although it should happen soon on wasp and surtur). However, the failure is easily reproducible, and this PR removes the package which is causing the failure. And CFS …
> CASMTRIAGE-5817: Remove csm-node-identity from package install lists for NCNs and Compute nodes

- CHANGELOG.md
- ansible/ncn_sysctl.yml
Somehow in the `git cherry-pick` the `ncn_sysctl.yml` playbook was set as a totally different file than what went into develop (see #164 and #163).
This corrects the content, as well as incorporating the fix from #168.
> CASMTRIAGE-5788 Fix `ncn_sysctl.yml`

- CHANGELOG.md
- ansible/ncn_sysctl.yml
The `&cfs_image` is breaking the `ncn_sysctl.yml` playbook
```bash
ERROR! Hosts list cannot be empty. Please check your playbook
```
The `&` is causing the YAML to read the value as an anchor, but in this case it is empty. Wrapping it in quotes prevents YAML from interpolating the value.
> CASMTRIAGE-5788 Fix YAML Anchor

- CHANGELOG.md
- zypper-docker-build.sh
Fix a build break caused by RPM locations changing to be in the `noos` repository
> CASMCMS-8691: Modify Dockerfile to account for changed RPM locations

- CHANGELOG.md
- ansible/ncn-master_nodes.yml
- ansible/ncn-storage_nodes.yml
- ansible/ncn-worker_nodes.yml
- ansible/ncn_nodes.yml
@## Summary and Scope
Makes `sysctl_set` dynamic based on whether an image is being built or if it is a running system.
* Resolves [CASMTRIAGE-5846](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5846)
Tested on Mug. Used CFS to apply role against `ncn-w002`. Used CFS to build a new image. Reverted code and used CFS to fail building a new image.
* Mug
> Change sysctl_set var to be dynamic depending on where it is executed

- CHANGELOG.md
- ansible/ncn-storage_nodes.yml
- ansible/ncn_nodes.yml
Summary and Scope
SuSmartmon role should not run during image customization
Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?
Issues and Related PRs
[List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies.](https://jira-pro.it.hpe.com:8443/browse/CASMMON-337)
Resolves -
https://jira-pro.it.hpe.com:8443/browse/CASMMON-337
Tested on mug
step 1: create json
```bash
cat ram.json
```
```json
{
"layers": [
{
"name": "configurations-layer-example-1",
"cloneUrl": "https://api-gw-service-nmn.local/vcs/cray/csm-config-management.git",
"playbook": "ncn_nodes.yml",
"branch": "ram"
}
]
}
```
step 2 create session
```bash
cray cfs sessions create --name "ram1" --configuration-name …
```
> CASMMON-337 Smartmon role should not run during image customization

- CHANGELOG.md
- Dockerfile
- Jenkinsfile.github
- ct.yaml
- zypper-docker-build.sh
This PR just backports several commits from the master branch that updated the Dockerfile (and associated scripts) to handle changes in the artifactory authentication and some changed RPM locations.
> Fix build break caused by artifactory authentication changes

- CHANGELOG.md
- ansible/csm_packages.yml
- ansible/vars/csm_packages.yml
* Resolves  - https://jira-pro.it.hpe.com:8443/browse/CASMMON-339
Shandy & Tyr
```text
PLAY [Application] *************************************************************
TASK [csm.gpg_keys : Fetch the HPE GPG Signing Key from the K8S secret] ********
ok: [x3000c0s23b0n0]
TASK [csm.gpg_keys : Create a temporary file to store the key content] *********
changed: [x3000c0s23b0n0]
TASK [csm.gpg_keys : …
```
> CASMINST-6624: Provide RPMs needed for enabling SMART data on UAN

- CHANGELOG.md
- ansible/vars/csm_packages.yml
Install `cray-uai-util` to both compute and application images.
* Resolves [CASMINST-6661](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6661)
* `beau`
* Virtual Shasta
Built an image on vshasta and verified the package was installed.
```
compute:~ # rpm -qa | grep uai
cray-uai-util-2.2.1-1.noarch
```
Low risk
> CASMINST-6661: Install UAI entrypoint package to compute

- CHANGELOG.md
- ansible/csm_packages.yml
The csm-node-identity and csm-node-heartbeat services recently changed names and are now owned by CSM. On managed nodes, these services are not being enabled. This PR updates the relevant CSM play to add these services to the list of CSM services that we enable on managed nodes.
This PR also changes how the `systemd` presets file is handled. First, instead of handling it with a large block of text, the line for each service is handled individually. Second, after the file is updated, `systemctl preset <whatever>.service` is invoked to apply the preset. This addresses the problem introduced by editing the presets file after the package has already been installed.
Resolves [CASMINST-6662](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6662)
I did some preliminary test of this on tyr, where …
> CASMINST-6662: Enable csm-node-heartbeat/csm-node-identity on managed nodes

- CHANGELOG.md
- ansible/roles/csm.ncn.cve_mitigations/tasks/main.yml
The version of ansible in the AEE in CSM-1.4 (and presumably CSM-1.3) have bugs related to the use of FQCNs. Stop using them.
* Resolves [MTL-2281](https://jira-pro.it.hpe.com:8443/browse/MTL-2281)
* `surtur` @ CSM-1.4.3-beta.4
Ran `apply_csm_configuration.sh` with my test branch.
N/A
> MTL-2281: don't use FQCNs; older CSM ansible versions have bugs

- CHANGELOG.md
- ansible/ims_computes.yml
- ansible/roles/csm.ims-remote/README.md
- ansible/roles/csm.ims-remote/defaults/main.yml
- ansible/roles/csm.ims-remote/tasks/main.yml
- ansible/vars/csm_ims_repos.yml
- ansible/vars/csm_packages.yml
Ansible play to customize an image with kata containers and install necessary packages to facilitate remote ims image building.
* Resolves [CASMCMS-8696](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8696)
Tested on mug.
Ran customizations on metal image on mug environment.
No
> CASMCMS-8696: Kata installation Ansible play

- CHANGELOG.md
- ansible/roles/csm.storage.smartmon/README.md
- ansible/roles/csm.storage.smartmon/defaults/main.yml
- ansible/roles/csm.storage.smartmon/tasks/main.yml
This change fixes the csm.storage.smartmon ansible. The Ceph command to redeploy node-exporter does not work when the ceph.client.admin.keyring is not present on the node. This change will only run the redeploy if the admin keyring is present.
* Resolves [CASMINST-6666](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6666)
* Beau - CSM 1.5 vShasta2
Ran a CFS session on a storage nodes with and without the admin keyring. Ensured the CFS role ran as expected.
When the Ceph admin keyring was present, I saw the following
```bash
TASK [csm.storage.smartmon : Check if ceph.client.admin.keyring exists on node] ***
ok: …
```
> CASMINST-6666 only have csm.storage.smartmon redeploy node-exporter if ceph admin keyring is present

- CHANGELOG.md
- ansible/vars/csm_packages.yml
Update to the latest curl to address CVE-2023-38545. The patched version of curl will be loaded into nexus.
Pairs with: https://github.com/Cray-HPE/csm/pull/2966
* Resolves CASMINST-6690
* `fanta`
> CASMINST-6690: update curl to address CVE-2023-38545

- CHANGELOG.md
- ansible/ncn-master_nodes.yml
- ansible/ncn-worker_nodes.yml
- ansible/ncn_nodes.yml
- ansible/roles/csm.ncn.sat/README.md
- ansible/roles/csm.ncn.sat/defaults/main.yml
- ansible/roles/csm.ncn.sat/tasks/main.yml
- ansible/roles/csm.ncn.sat/vars/main.yml
- ansible/vars/csm_packages.yml
Add a `csm.ncn.sat` role to configure SAT on Kubernetes management NCNs (masters and workers). This role is being moved from the separate sat-config-management repository into this repository as part of the effort to fully merge the SAT product into the CSM product.
The main differences between the Ansible content as it existed in the SAT product stream and the content added here are as follows:
- The version of the `cray-sat` container image is injected using an initContainer in the Helm chart and a loftsman manifest customization in the CSM release build process.
- There is no longer a separate package repository in Nexus that must be added on management NCNs. The `cray-sat-podman` package is included in the CSM noos repository, and it is installed with the existing csm.packages role. …
> CRAYSAT-1767: Add csm.ncn.sat role to configure SAT

- CHANGELOG.md
- ansible/roles/csm.storage.smartmon/tasks/main.yml
Deploy node-exporter via cephadm shell in ansible that deploys smartmon on storage nodes.
We believe this change is necessary because when applying the CSM 1.4.2 patch on Alvarez, the smartmon enablement on storage nodes script failed. This was likely caused by the ceph-common version on the system. To be able to apply the node-exporter.yml file which enables smartmon, node-exported was deployed via cephadm shell. Applying node exporter via the cephadm shell should work every time and doesn't depend on the ceph-common version installed on the node.
This has been tested on Beau.
* Resolves [CASMPET-6860](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6860)
_List the …
> CASMPET-6860 deploy node-exporter via cephadm shell in ansible

- CHANGELOG.md
- ansible/roles/csm.storage.smartmon/tasks/main.yml
Deploy node-exporter via cephadm shell in ansible that deploys smartmon on storage nodes.
We believe this change is necessary because when applying the CSM 1.4.2 patch on Alvarez, the smartmon enablement on storage nodes script failed. This was likely caused by the ceph-common version on the system. To be able to apply the node-exporter.yml file which enables smartmon, node-exported was deployed via cephadm shell. Applying node exporter via the cephadm shell should work every time and doesn't depend on the ceph-common version installed on the node.
This has been tested on Beau.
* Resolves [CASMPET-6860](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6860)
_List the …
> CASMPET-6860 release/1.16-Deploy node-exporter via cephadm shell in ansible

- CHANGELOG.md
- ansible/roles/csm.storage.smartmon/defaults/main.yml
- ansible/roles/csm.storage.smartmon/tasks/main.yml
**Problem**
On a storage node upgrade on Starlord, cephadm used the incorrect image when trying to redeploy node-exporter. This was likely due to the fact that midway through a storage node upgrade, the cephadm version installed on the node is at a higher version than the Ceph container version that is running. This causes cephadm to look for a default image at 'docker://quay.io/ceph/ceph:v17' which it is unable to find and caused the ansible play to fail.
**Solution/Change**
We can specify the container image that cephadm should use which means it should not look for this default image.
**Notes**
We were not able to prove why cephadm was looking for the ceph image at 'docker://quay.io/ceph/ceph:v17'. I have not replicated this problem and checked that this is indeed the solution. …
> CASMTRIAGE-6370 update csm.storage.smartmon to use specific ceph image when redeploying node-exporter

- CHANGELOG.md
- ansible/ncn-initrd.yml
- ansible/roles/ncn_kernel_upgrade/defaults/main.yml
- ansible/roles/ncn_kernel_upgrade/handlers/main.yml
- ansible/roles/ncn_kernel_upgrade/tasks/main.yml
New roles and updates to `ncn_initrd.yml` for installing new packages pertaining to NIC
failures:
- New SuSE PTF Kernel mitigating Kernel Panics for any vendor during NIC recovery
- New Marvell driver with bugfixes for successfully recovering bonded QLogic NICs
System: groot
Resulting `rootfs` had:
- New QLogic KMP
- New Kernel
- All old kernels were purged
- `multiversion.kernels` was updated in `/etc/zypp/zypp.conf`
- `qedr` appeared in both `/etc/modprobe.d/disabled-modules.conf` and `/etc/dracut.conf.d/99-csm-ansible.conf`
- `/etc/dracut.conf.d/fastlinq.conf` was removed
```bash
ncn-m001:/ # rpm -qa kernel-default
kernel-default-5.14.21-150400.24.100.2.27359.1.PTF.1215587.x86_64
ncn-m001:/ # rpm -qa qlgc
ncn-m001:/ # rpm -q qlgc-fastlinq-kmp-default …
```
> MTL-2348 Marvell/SuSE Fixes for Failed NIC Recovery

- CHANGELOG.md
- ansible/roles/ncn_kernel_upgrade/defaults/main.yml
- ansible/roles/ncn_kernel_upgrade/tasks/main.yml
QLogic cards are not showing in the initramfs, the `qede` module is
failing to load.
This was root caused by the removal of `fastlinq.conf`.
We still have to remove `fastlinq.conf`, as it installs `qedr` and
overrides our blacklist.
The QLogic modules must be specified for the necessary weak-updates to be installed into the initramfs.
This adds all the modules from `fastlinq.conf`, excluding `qedr`.
> MTL-2348 Fixes QLogic Boots

- CHANGELOG.md
- ansible/csm_packages.yml
This fixes the issues related to the spire-agent change over. It adds some new links to allow for services to pull the correct spire-agent during install time.
* Resolves [CASMTRIAGE-6582](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6582)
* Noname
> CASMTRIAGE-6582: Fix spire-agent dependencies

- CHANGELOG.md
- ansible/ims_computes.yml
Simple uncontroversial typo fix
> CASMCMS-8924: Fixed typo in ansible/ims_computes.yml

- CHANGELOG.md
- ansible/csm_packages.yml
Password-less ssh to CN/UAN is moved to CSM layer from USS layer.
This change backwards compatible and have it should not affect the older compute node config.
* Resolves [SKERN-9239](https://jira-pro.it.hpe.com:8443/browse/SKERN-9239)
CFS layers for USS and CSM needs to be manually applied to Odin's CN/UAN configurations.
* `Odin`
Generated boot image using the updated CFS configs, booted CN/UAN to make sure password-less ssh works.  Ansible log is verified for this move.
USS will remove the passwordless config from USS layer and it depends on this mod to make the CN/UAN passwordless to work.
> SKERN-9239: Added password-less ssh to CN/UAN to CSM layer

- CHANGELOG.md
- ansible/roles/csm.ca_cert/tasks/main.yml
The newest ca-certificates rpm uses/requires the **statedir** environment variable to be set. Under normal circumstances the update-ca-certificates script sets the variable and executes all of the *.run scripts in /usr/lib/ca-certificates/update.d/.  Since we don't use the update-ca-certificates script, we have to set the statedir variable. The changes in this PR are backwards compatible.
This statedir variable change was introduced in ca-certificates-2+git20240416.98ae794-150300.4.3.3
We are currently running ca-certificates-2+git20210309.21162a6-2.1
https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6992
* gamora
The ca-cert ansible role was modified with the same changes in this PR. The play was successful.
None known.
> CASMTRIAGE-6992

- CHANGELOG.md
- ansible/compute_nodes.yml
- ansible/roles/csm.gpg_keys/README.md
- ansible/roles/csm.gpg_keys/defaults/main.yml
- ansible/roles/csm.gpg_keys/tasks/install_key.yml
- ansible/roles/csm.gpg_keys/tasks/main.yml
- ansible/roles/csm.packages/meta/main.yml
Add multiple GPG keys via CFS
Most of this code was written by @mtupitsyn, I just borrowed it.
- https://jira-pro.it.hpe.com:8443/browse/CASMINST-6896
- This is targeted for CSM 1.5. It is a backport of: https://github.com/Cray-HPE/csm-config/pull/277
node-personalization and image customization were both successful
- tyr
none known
> CASMINST-6896: Support multiple GPG signing keys and install them

- CHANGELOG.md
- ansible/ncn_nodes.yml
- ansible/roles/csm.ncn.fs_mount_options/defaults/main.yml
- ansible/roles/csm.ncn.fs_mount_options/tasks/main.yml
- ansible/vars/csm_packages.yml
re-adding the XFS mount changes that were removed in https://github.com/Cray-HPE/csm-config/pull/282
https://jira-pro.it.hpe.com:8443/browse/MTL-2405
none
> MTL-2405 - re-add XFS mount changes

- CHANGELOG.md
- ansible/config_sbps_iscsi_targets.yml
- ansible/roles/csm.gpg_keys/tasks/main.yml
- ansible/roles/csm.sbps.dns_srv_records/files/sbps_dns_srv_records.sh
- ansible/roles/csm.sbps.enable_spire/README.md
- ansible/roles/csm.sbps.enable_spire/tasks/main.yml
- ansible/roles/csm.sbps.install_enable_marshal/README.md
- ansible/roles/csm.sbps.install_enable_marshal/tasks/main.yml
- CASMPET-7180: New CFS play for enabling spire for SBPS Marshal Agent
- CASMPET-7195: New CFS play for install (+ previous enable) SBPS Marshal Agent
- typo fix in DNS SRV A records creation
- updated CHANGELOG.md
Part of the iSCSI SBPS feature:
- Added new CFS play for enabling spire for SBPS Marshal Agent
- Added new CFS play for installing SBPS Marshal Agent (+ previous SBPS Marshal Agent enable/ start)
- Fixed typo in DVS SRV and A records creation
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue …
> - CASMPET-7180: New CFS play for enabling spire for SBPS Marshal Agent

- CHANGELOG.md
- ansible/ncn_hsn_bonding.yml
- ansible/roles/csm.ncn.hsn_bonding/README.md
- ansible/roles/csm.ncn.hsn_bonding/defaults/main.yml
- ansible/roles/csm.ncn.hsn_bonding/handlers/main.yml
- ansible/roles/csm.ncn.hsn_bonding/tasks/main.yml
- ansible/roles/csm.ncn.hsn_bonding/templates/bond.j2
- ansible/roles/csm.ncn.hsn_bonding/templates/macvlan.j2
- ansible/roles/csm.ncn.hsn_bonding/templates/script.j2
Ansible role to configure a bonded HSN interface on NCNs.
This role is not enabled by default as it requires values that have to be supplied by the Slingshot administrator.
* Resolves [MTL-1980](https://jira-pro.it.hpe.com:8443/browse/MTL-1980)
* Documentation changes to follow in [MTL-1981](https://jira-pro.it.hpe.com:8443/browse/MTL-1981)
* `surtur`
Rebuilt ncn-w005 with Playbook enabled with the following settings
```
hsn_bond_mac: "b2:00:00:00:00:01"
hsn_bond_ip: "10.253.254.1"
hsn_bond_netmask: '255.255.0.0'
hsn_bond_enable: true
```
Verified bond was configured as expected.
```
Running ncn_hsn_bonding.yml from repo https://api-gw-service-nmn.local/vcs/cray/csm-config-management.git
[WARNING]: Could not match supplied host pattern, ignoring: cfs_image
PLAY [Configure HSN bonding] …
```
> MTL-1980 - Configure a bonded HSN connection on an NCN

- CHANGELOG.md
- ansible/config_sbps_iscsi_targets.yml
[CASMPET-7225](https://jira-pro.it.hpe.com:8443/browse/CASMPET-7225): Fallback to default IMS user policy for CPS
We must have writable access to "/var/lib/cps-local/boot-images" mount directory of "boot-images" bucket order for CPS to function. CPS creates cos-config-data under "/var/lib/cps-local/boot-images"(information for the contents projected by DVS.  User also need write access while removing cos-config-data under "/var/lib/cps-local/boot-images", when he wants to disable CPS.
Since for CSM-1.6 and USS-1.2 we are supporting CPS, we need to make it writable.  When CPS will be removed in USS-1.3, we can fallback again to dedicated s3fs read-only policy.
* Resolves [issue …
> iSCSI SBPS: Fallback to default IMS user policy for CPS

- CHANGELOG.md
- ansible/config_sbps_iscsi_targets.yml
This change updated the hosts stanza for the SBPS playbook so that if the playbook is run during image personalization using CFS/IMS the playbook won't attempt to run.   This is to allow the playbook to be added to the sat bootprep files we provide with the release.
This change should not create any backward compatibility issues as the config_sbps_iscsi_targets.yml playbook has only been used on running nodes and is documented as working that way.
This change should not be dependent on any other changes that are in flight.
This change was tested on gamora during image personalization and node customization and worked as expected.
* gamora
The updated playbook was tested during image customization and node personalization and worked appropriately in each instance.
- Were the …
> CASMPET-7254 update hosts so CFS skips image personalization

- CHANGELOG.md
- ansible/csm_packages.yml
The iscsid service is the control path for iSCSI. It needs to be running when we are using iSCSI projection, so that if the worker nodes (target side) are rebooted or rebuilt, the iSCSI sessions will be recovered on the compute/UAN.
We also need to enable multipathd for when we are running with USS 1.1 for the hybrid solution (need SP5 on compute nodes for NVIDIA support).
* Resolves [CASMTRIAGE-7459](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7459)
* `gamora`
This change (having the `iscsid` service running) has been tested on `fanta`, `drax`, and `gamora`.  When the `iscsid` service is running in the compute/UAN, then when a worker node is rebooted or rebuilt, the `iscsid` service is notified by the kernel of the …
> CASMTRIAGE-7459 iscsid needs to run on compute/UAN

- CHANGELOG.md
- ansible/vars/csm_packages.yml
When doing 1.5.3 testing, we discovered that an ARM image customization failed because it could not install the cfs-debugger RPM. This package mainly makes sense to install on the NCNs, as debugging CFS issues is generally a task done by system administrators. This PR changes the Ansible so that it only installs the RPM on management NCNs.
> CASMCMS-9258: Only install cfs-debugger RPM on management NCNs

- CHANGELOG.md
- ansible/roles/csm.sbps.dns_srv_records/files/sbps_dns_srv_records.sh
CSM 1.6 backport of https://github.com/Cray-HPE/csm-config/pull/342
> CASMPET-7443/CASMPET-7444: iSCSI SBPS projection over NMN will fail if DNS "A" (address) records for NMN are not created

- CHANGELOG.md
- ansible/config_sbps_iscsi_targets.yml
Currently on worker node are configured for iSCSI (iSCSI target) via node personalization. As all nodes are not required to be iSCSI targets, we need to have selective worker node personalization. This is achieved by creating HSM groups. 
* Resolves [issue id](issue link): CASMPET-7260
* Change will also be needed in `<insert branch name here>`: N/A 
* Future work required by [issue id](issue link): N/A 
* Documentation changes required in [issue id](issue link): CASMPET-7556
* Merge with/before/after `<insert PR URL here>`: N/A
Testing is done on drax, tyr and starlord. 
Tested on drax (CSM 1.6.2-rc.1), Tyr (CSM 1.6.1-rc.7) and starlord (CSM 1.7.0-alpha.11)
Tested on drax (CSM 1.6.2-rc.1), Tyr (CSM 1.6.1-rc.7) and starlord (CSM 1.7.0-alpha.11)
Created HSM group having single and dual …
> CASMPET-7260: During bootprep provide a method to select specific worker nodes for node personalization

- CHANGELOG.md
- ansible/config_sbps_iscsi_targets.yml
- ansible/roles/csm.sbps.lio_config/files/provision_iscsi_server.sh
Worker node hung due to flood of NON_EXISTENT_LUN messages with rebuild of the node.
- Changed the order of iSCSI ansible play books execution where LIO config is first and then SBPS Mrashal agent installation and configuration
- Disable the target port after the portals are created
- The fix is spread across 'csm-config' repo as well as 'sbps-marshal' repo
The fix is spread across "csm-config" repo and "sbps-marsha" repo for which PR to be raised.
* Resolves [CASMTRIAGE-8171](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-8171)
* Change will also be needed in `<insert branch name here>`: N/A
* Future work required by [issue id](issue link): N/A 
* Documentation changes required in [issue id](issue link): N/A 
* Merge with/before/after `<insert PR URL here>`: N/A 
Unit test results …
> Casmtriage 8171 fix

- CHANGELOG.md
- ansible/config_sbps_iscsi_targets.yml
- ansible/roles/csm.sbps.apply_label/README.md
- ansible/roles/csm.sbps.apply_label/defaults/main.yml
- ansible/roles/csm.sbps.apply_label/tasks/main.yml
- ansible/roles/csm.sbps.dns_srv_records/files/sbps_get_host_hsn_nmn.sh
This modifies the main iSCSI playbook so that it runs on all worker nodes. However, its behavior on them is now different based on the new HSM group.
For all changes described here, if the HSM group does not exist, then it works exactly the same as if the HSM group exists and all workers belong to it.
The `apply_label` role now both adds or removes the iSCSI Kubernetes label. For all nodes in the group, it is added, and for all nodes not in the group, it is removed. 
In the process of making this change, I also got rid of the previous shell script, and implemented this using the Ansible kubernetes module.
Right now this is being done on each worker node, but a good improvement to this would be to have this just run once on a single node, since nothing it is doing involves the actual node …
> CASMPET-7616: Modify iSCSI playbook to be aware of new HSM group

- CHANGELOG.md
- ansible/config_sbps_iscsi_targets.yml
- ansible/roles/csm.sbps.apply_label/README.md
- ansible/roles/csm.sbps.apply_label/tasks/main.yml
- ansible/roles/csm.sbps.apply_label/tasks/update_labels.yml
Currently, the apply_labels step does its execution on the target worker NCN. This means that for workers that are down, it will not change their labels.
This PR changes it so that the apply_labels role runs locally inside the CFS pod. Additionally, it will update the labels for all workers, whether or not they are up when the play runs, or even if they are not one of the hosts targeted for the play. Basically, any time this role runs, it sets/removes the Kubernetes tags for all of the workers.
For the good path (where all nodes are up), there will be no change in the ultimate behavior of the play (although the CFS logs will look different).
An example of the new role running:
```
TASK [csm.sbps.apply_label : All workers are intended for iSCSI by default] ****
ok: [x3000c0s11b0n0 -> …
```
> CASMPET-7624/CASMPET-7625: apply_label role improvements

- CHANGELOG.md
- ansible/roles/csm.rr.mgmt_nodes_placement_discovery/files/rack_to_node_mapping.py
- ansible/roles/csm.rr.mgmt_nodes_placement_discovery/tasks/main.yml
[CASM-5685](https://jira-pro.it.hpe.com:8443/browse/CASM-5685): RR storage play still assumes kubectl configured on all storage nodes
The csm.rr.mgmt_nodes_placement_discovery role uses kubectl command to run on the management nodes to get Kubernetes info and that needs to change to use native Ansible inside the CFS pod to get the information from Kubernetes in order to avoid any failures on management nodes (Master and Storage nodes) which are not configured with kubectl.
[CASM-5685](https://jira-pro.it.hpe.com:8443/browse/CASM-5685)
Wasp bare metal.
Tested Ansible plays deployments with CFS.
**Verifying on Storage nodes:**
Fanta has only 3 storage nodes as below. We have tested CFS to make it runs on storage node-3 (mention of XNAME during management rollout) and it has been successful. …
> CASM-5685: RR storage play still assumes kubectl configured on all storage nodes

- CHANGELOG.md
- ansible/roles/csm.sbps.dns_srv_records/files/sbps_dns_srv_records.sh
This PR makes 3 changes to the `sbps_dns_srv_records.sh` script:
1. Prior to this PR, the script made no checks to ensure that `SYSTEM_NAME` or `SITE_DOMAIN` are set to non-empty values. If they are blank, it will either cause the script to fail, or (worse) the script would pass but not actually update the DNS records correctly. This PR changes it so that it checks if these are blank, and if they are, it will exit with an appropriate error message.
2. Numerous `echo` statements added, so that the output of the script shows what is happening. This is important because prior to this PR, when the script fails, the only information you have to go on is whatever error message was given by the thing that caused it to fail. This may not be very descriptive; it may not be obvious which specific …
> CASMPET-7660: Make sbps_dns_srv_records.sh more verbose
