README.md
To resolve CVE vulnerabilities, this needed to incorporate a new base image and a new security patched version of cf-gitea-import.  There are no code changes, just a triggered rebuild to incorporate the patched dependent images.
* Resolves [CASMCMS-7819](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7819)
I verified the new images are free of known vulnerabilities using the snyk tool on the Jenkins built images.  As there are no code changes I did not test on a machine.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? N
- Was upgrade tested? If not, why? N
- Was downgrade tested? If not, why? N
- Were new tests (or test issues/Jiras) created for …
=> CASMCMS-7819 - Trivial change to force rebuild.

README.md, ansible/vars/csm_packages.yml, update_external_versions.conf
Take the collected changes from release/csm-1.2 that have not been merged to master and get them moved over.
Not tested - just merging already tested changes.
Low risk - this will be completely tested in powerDNS transition work.
=> Merge changes from release/csm-1.2 into master.

ansible/roles/csm.ssh_keys/tasks/main.yml
Backport https://github.com/Cray-HPE/csm-config/pull/49 into csm-1.2
See main PR for details.
https://github.com/Cray-HPE/csm-config/pull/49
See main PR for details.
Low risk.
=> CASMCMS-7990: Append newline to SSH key files

.github/workflows/csm-changelog-checker.yml, .github/workflows/gitflow-mergeback.yml, CHANGELOG.md, GitVersion.yml
Merges develop to master to pull in the files for gitflow
NA - build only
None
=> Convert repo to gitflow

CHANGELOG.md
Releases 1.10.0
Includes the changelog update for gitflow conversion and the csm playbook
* Resolves CASMCMS-6989
NA - changelog/release
None
=> 1.10.0 release

CHANGELOG.md
- CASMCMS-8209: Add csm-sle15sp4 repo
- Prepare 1.14.0 release
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* `<development system>`
* Virtual Shasta
_How were …
=> Release 1.14.0

CHANGELOG.md, CONTRIBUTING.md
This file points at our Gitflow process to help developers outside our group use our code.
* Resolves nothing.
It's a readable file. I read it.
As low as humanly possible...
=> Add a contributing.md file

CHANGELOG.md, ansible/vars/csm_repos.yml
Add the CSM embedded repo. This repo contains all of the RPMs that are installed on the NCNs.
* Resolves [CASMINST-6051](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-6051)
* TBD
Needs testing
N/A
=> CASMINST-6051: add the CSM embedded repo

CHANGELOG.md, ansible/vars/csm_packages.yml
Include `csm-node-identity` and `spire-agent`.
=> MTL-2014 MTL-2025

CHANGELOG.md, ansible/vars/csm_packages.yml
Add packages recently transferred from COS to CSM.
https://jira-pro.it.hpe.com:8443/browse/MTL-2018
https://jira-pro.it.hpe.com:8443/browse/MTL-2019
- built image
- tyr
=> add csm packages

CHANGELOG.md, ansible/ncn-master_nodes.yml, ansible/ncn-storage_nodes.yml, ansible/ncn-worker_nodes.yml, ansible/ncn_nodes.yml, ansible/packages.yml, ansible/vars/csm_packages.yml
Implement some good suggestions from Ryan to improve [my recent modifications](https://github.com/Cray-HPE/csm-config/pull/143).
* Resolves [CASMINST-6535](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6535)
=> CASMINST-6535: Reorganize plays in ncn_nodes.yml to optimize package installs; rename two package lists

CHANGELOG.md, ansible/vars/csm_repos.yml
This change is related to the effort behind MTL-2000 and CASMINST-3431, where we can cease including every single SLE distribution (e.g. including sle-15sp2 repo on a running sle-15sp4 distro). The change here will ensure that only the following repositories are added:
- The embedded repo
- The noos repo
- The running distro's repo
This is more than a "tidy up" task, it fixes a bug where a package that does care about the distro is incorrectly resolved by Zypper. There are a few packages that do need to come from the running distro's repos, and adding mismatching distro repos causes problems.
Example, libcsm resolves from the wrong repository (sle-15sp3) and …
=> MTL-2000 CASMINST-3431 Do not add every SLE repo; only add corresponding SLE repo

CHANGELOG.md, ansible/ncn-storage_nodes.yml, ansible/ncn_nodes.yml
See https://github.com/Cray-HPE/csm-config/pull/183
=> CASMMON-337: Smartmon role should not run during image customization

CHANGELOG.md, ansible/ncn-master_nodes.yml, ansible/ncn-storage_nodes.yml, ansible/ncn-worker_nodes.yml, ansible/roles/csm.ncn.cve_mitigations/README.md, ansible/roles/csm.ncn.cve_mitigations/tasks/main.yml
Add a new role for mitigating CVEs
* Resolves [MTL-2216](https://jira-pro.it.hpe.com:8443/browse/MTL-2216)
* `surtur`
N/A
=> MTL-2216: ansible to apply zenbleed mitigation

CHANGELOG.md, ansible/roles/csm.ncn.cve_mitigations/tasks/main.yml
Fix env var that was lost while moving code around.
* Resolves MTL-2126
* `surtur`
=> MTL-2216: fixup missing env var

CHANGELOG.md, ansible/roles/csm.ncn.cve_mitigations/tasks/main.yml
Environment variable definition was lost while moving code around.
* Resolves MTL-2215
* `surtur`
=> MTL-2215: fixup

CHANGELOG.md, ansible/csm_packages.yml, ansible/vars/csm_packages.yml
Revert SMART-related changes that were unintentionally merged into 1.14 branch for CSM 1.3
=> Revert CASMINST-6624

CHANGELOG.md, ansible/vars/csm_packages.yml
Add new RPMs to the CSM config for enablement of TPM on compute nodes.
* Resolves [CASMPET-6814](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6814)
* Baldar
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?y
- Were continuous integration tests run? If not, why?y
- Was upgrade tested? If not, why?y
- Was downgrade tested? If not, why?y
- Were new tests (or test issues/Jiras) created for this change?y
Low risk only adds functionality
=> CASMPET-6814: Add required TPM related packages

CHANGELOG.md, ansible/ims_computes.yml, ansible/roles/csm.ims-remote/defaults/main.yml, ansible/roles/csm.ims-remote/tasks/main.yml, ansible/vars/csm_ims_repos.yml
Modified the ims remote play to configure an arm based compute.
https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8824
Mug/Baldar/Tyr
Tested play execution against bare metal image from the metal team as well as an IMS built barebones image.
No
=> Casmcms 8824

CHANGELOG.md, ansible/ims_computes.yml, ansible/roles/csm.ims-remote/defaults/main.yml, ansible/roles/csm.ims-remote/tasks/main.yml, ansible/vars/csm_ims_repos.yml
Modified the ims remote play to configure an arm based compute.
https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8824
Mug/Baldar/Tyr
Tested play execution against bare metal image from the metal team as well as an IMS built barebones image.
No
=> aarch64 ims remote builder node config for 1.5

CHANGELOG.md, ansible/ims_computes.yml, ansible/roles/csm.ims-remote/defaults/main.yml, ansible/roles/csm.ims-remote/tasks/main.yml
Utilize CSM trust ssh keys and add passwordless ssh role.
https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6948
Drax
Play application. Node boot and testing both csm and ims key
None
=> Casmtriage 6948

CHANGELOG.md, ansible/ncn_nodes.yml, ansible/roles/csm.ncn.fs_mount_options/defaults/main.yml, ansible/roles/csm.ncn.fs_mount_options/tasks/main.yml, ansible/vars/csm_packages.yml
- add role for setting xfs mount options to 'defaults' for /var/lib/containers
https://jira-pro.it.hpe.com:8443/browse/MTL-2390
- ran CFS image customization on tyr
- local dev machine
- tyr
none known
=> MTL-2390 -- 1.15 -- csm-1.4

CHANGELOG.md, ansible/roles/csm.ca_cert/tasks/main.yml
backport of https://github.com/Cray-HPE/csm-config/pull/265
=> CASMTRIAGE-6992 - 1.5.2

CHANGELOG.md, Dockerfile, zypper-docker-build.sh
This is to prevent the build from failing.
=> CASMCMS-9114: Build Docker image on SLE15 SP6 (up from SP4)

CHANGELOG.md, ansible/vars/csm_packages.yml
CSM 1.6 backport of https://github.com/Cray-HPE/csm-config/pull/332
=> CASMCMS-9262: Update RPM lists in vars/csm_packages.yml

CHANGELOG.md, ansible/roles/csm.ncn.sysctl/vars/main.yml
add net.ipv4.neigh.default.base_reachable_time_ms to sysctl settings
https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-8069
Thoroughly tested by Harold L. 
None known
=> CASMTRIAGE-8069

CHANGELOG.md, ansible/ncn_nodes.yml, ansible/vars/csm_packages.yml
Install RPM's transferred from COS:
https://jira-pro.it.hpe.com:8443/browse/MTL-2555
https://jira-pro.it.hpe.com:8443/browse/MTL-2556
https://jira-pro.it.hpe.com:8443/browse/MTL-2569
https://jira-pro.it.hpe.com:8443/browse/MTL-2573
https://jira-pro.it.hpe.com:8443/browse/MTL-2574
- tyr
NCN and CN images were built for x86_64 / aarch64
nodes were booted, RPM installation and functionality were verified
=> MTL-2569 / MTL-2574 / MTL-2556 / MTL-2555 / MTL-2573

CHANGELOG.md, ansible/csm_packages.yml, ansible/vars/csm_packages.yml
* Resolves - https://jira-pro.it.hpe.com:8443/browse/CASMMON-548
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* `<development system>`
* Virtual Shasta
_How were the changes tested and success …
=> CASMMON-548: UAN image creation is failing during prepare images
